<?php

/**
 * @file
 * Code for the OS2Web Meeting Views feature.
 */

include_once 'os2web_meetings_light.features.inc';

/**
 * Implements hook_os2web_help().
 */
function os2web_meetings_light_os2web_help($sections) {

  // Content types.
  $sections['contenttype'] = t('<p><b>Meetings:</b> Dependent on the system, meetings are often imported by a meeting importer, which can communicate with your ESDH.<br />A meeting contains bullets which can contain attachments. These are all imported, and should not be altered directly on site.<br />See the <a href="@url" target="_blank">overview</a> over meetings.</p>', array('@url' => url('dagsorden-og-referat')));
  return $sections;
}
